### ISSUE TITLE
Zooming past the lowest limits and highest limits is possible

### ISSUE THREAD

**Issue by cmdcolin** [cytoscape/cytoscape.js-panzoom#17]
If you zoom to the max level on the slider, it is possible to still zoom in even further. I wasn't sure if maxZoom and minZoom are the true limits or or those are not being checked, causing this behavior?

**Comment by maxkfranz** [comment]
The library has its own max and min values, which can not be contradicted.  The options in the extension are just for the UI.  I suppose the extension could just use the values from lib, but the issue is that the value can be changed by the dev over time.  Maybe it should use the core values by default but still allow manual setting?
