### ISSUE TITLE
Is the panzoom behavior reversed ?

### ISSUE THREAD

**Issue by jerishsd** [cytoscape/cytoscape.js-panzoom#22]
When pressing the down arrow, graph moves up, up arrow graph moves down.
(External fiddle : http://jsfiddle.net/ajhnmcrb/11/ discussed in https://github.com/cytoscape/cytoscape.js/issues/1322)
Flipped the signs in handle2pan & positionIndicator to fix it. (Code snippets below).
Is this a known issue ?

            var vnorm = {
              x: +1 * v.x * (percent * options.panDistance),
              y: +1 * v.y * (percent * options.panDistance)
            };

            var vnorm = {
              x: +1 * v.x/d,
              y: +1 * v.y/d
            };

**Comment by maxkfranz** [comment]
No, it's correct.  Users click up when they want to see content that's hidden upwards.  It's the same as map apps, like Google Maps or Bing Maps.  It's what old fashioned users expect, because it's the most common convention for those widgets.  The only reason to use an extension like this is to cater to old fashioned users anyway, as users by and large prefer to just use faster and more natural built-in gestures.  Even Google maps and Bing maps don't include panzoom controls anymore.

**Comment by jerishsd** [comment]
Thanks much Max for the quick response, and the background :)
Makes sense :)
Checked out mapquest and the behavior is the same, 
https://www.mapquest.com/directions
